#!/bin/bash


# Create a bash script that:
# Copies /var/log/syslog to the current working directory
# Appends the current date and time to the filename


# setting source and destination along with adding date to destination file name

source="/var/log/syslog"
current_date=$(date +"%T%m%d_%H%M%S")
destination="Log_${current_date}.log"

# copy the syslog with current date and add to working directory
cat "$source" >> "$destination"