#!/bin/bash


# Menu options
echo "Menu"
echo "1. Hello world!"
echo "2. Ping self"
echo "3. IP info"
echo "4. Exit"

# Ask for user input

read -p "Please select an option: " input

#process user input

case $input in
    1)
        echo "Hello world!"
        ;;
    2)
        ping -c 4 127.0.0.1
        ;;
    3)
        ifconfig -a
        ;;
    4)
        echo "Exiting"
        exit 0
        ;;
    *)
        echo "Invalid option. Please choose a valid option"
        ;;
esac
